import type { Metadata } from "next";
import { Bangers, Quicksand, Roboto_Condensed } from "next/font/google";
import Nav from "./components/Nav";
import "./globals.css";

const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand',
})

const bangers = Bangers({
  subsets: ['latin'],
  variable: '--font-bangers',
  weight: ['400'],

})

const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'],
  variable: '--font-robotoCondensed',
  weight: ['300', '400', '700'],
})

export const metadata: Metadata = {
  title: "Pizzaria Novo Sabor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} ${bangers.variable} ${robotoCondensed.variable} antialiased font-quicksand`}
      >
        <Nav/>
        {children}
      </body>
    </html>
  );
}
